[project]
name = "py-scrobbler"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.5",
    "asyncpg>=0.31.0",
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "py-applescript>=1.0.3",
    "pydantic>=2.13.4",
    "pylast>=7.0.2",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "spotipy>=2.26.0",
    "sqlalchemy[asyncio]>=2.0.49",
    "textual>=8.2.7",
    "uvicorn[standard]>=0.47.0",
]
